### ISSUE TITLE
Implementing Drag and Drop - Project Source runtime error

### ISSUE THREAD

**Issue by rusmo** [survivejs/webpack_react#232]
After running into this error while going through the tutorial, I got latest (v1.7.6) and got an error in Chrome doing the following in the kanban_app folder:

npm install
npm start
browse to localhost:8080

The screen is blank and I get this error:

TypeError: Cannot read property 'id' of undefined in Notes.jsx?d551:20

````
  renderNote(note) {
    return (
      <Note className='note' onMove={LaneActions.move}
        data={note} key={`note${note.id}`}>  // line 20
        <Editable
          value={note.task}
          onEdit={this.props.onEdit.bind(null, note.id)}
          onDelete={this.props.onDelete.bind(null, note.id)} />
      </Note>
    );
  }
````

**Comment by bebraw** [comment]
Thanks for the report.

I think it's fixed in `dev` branch as we went through the chapter and cleaned up things a bit. I'll leave this open till a new version goes out (hopefully within a couple of days).

**Comment by rusmo** [comment]
Thanks. I just pulled down the dev branch and I'm still seeing the error. Let me know it's working for you.

**Comment by bebraw** [comment]
@rusmo Thanks for letting me know. Based on the error I would say it's missing some check. I'll get this fixed. :+1:

**Comment by bebraw** [comment]
@rusmo Works for me (erased `localStorage` and started from scratch). We could try to make `NoteStore.get` more robust. Try this:

**app/stores/NoteStore.js**

```
  get(ids) {
    return (ids || []).map((id) => this.notes[this.findNote(id)]).filter((a) => a);
  }
```

That should filter out any notes that are `undefined`, `null` or such. I'm not sure how they can get set like that, though.

**Comment by rusmo** [comment]
The new implementation of get(ids) worked - thanks!

**Comment by bebraw** [comment]
Ok. It would be very useful if we knew what caused the invalid data in the first place but this will do for now. The fix will be included in the next release.
